language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install pytest-cov
script:
    - pip install -e .
    - py.test --cov fridge fridge
    - py.test systemtests
after_success:
    coveralls
